CREATE TABLE `tweet_posts` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`post` VARCHAR(180) NULL DEFAULT NULL,
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)

CREATE TABLE `tweet_users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name_surname` VARCHAR(200) NULL DEFAULT NULL,
	`username` VARCHAR(200) NULL DEFAULT NULL,
	`password` VARCHAR(200) NULL DEFAULT NULL,
	`email` VARCHAR(100) NULL DEFAULT NULL,
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
