CREATE TABLE `tweet_posts` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`post` VARCHAR(180) NULL DEFAULT NULL,
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)

CREATE TABLE `tweet_posts` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`post` VARCHAR(180) NULL DEFAULT NULL,
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE `tweet_follow` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`followup_id` INT(11) NOT NULL,
	`followed_id` INT(11) NOT NULL,
	`state` TINYINT(4) NOT NULL,
	PRIMARY KEY (`id`)
);


