CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`surname` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` CHAR(32) NOT NULL,
	`last_move` DATETIME NULL DEFAULT NULL,
	`created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)

CREATE TABLE `todos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`categori_id` INT(11) NULL DEFAULT NULL,
	`title` VARCHAR(255) NULL DEFAULT NULL,
	`description` TINYTEXT NULL,
	`color` VARCHAR(50) NULL DEFAULT NULL,
	`end_date` DATETIME NULL DEFAULT NULL,
	`start_date` DATETIME NULL DEFAULT NULL,
	`created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)

CREATE TABLE `categories` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`title` VARCHAR(255) NULL DEFAULT NULL,
	`created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)

CREATE TABLE `todos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NULL DEFAULT NULL,
	`category_id` INT(11) NULL DEFAULT NULL,
	`title` VARCHAR(255) NULL DEFAULT NULL,
	`description` TINYTEXT NULL,
	`color` VARCHAR(50) NULL DEFAULT NULL,
	`end_date` DATETIME NULL DEFAULT NULL,
	`start_date` DATETIME NULL DEFAULT NULL,
	`created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`progress` TINYINT(4) NULL DEFAULT NULL,
	`status` ENUM('a','p','s') NULL DEFAULT 'a',
	PRIMARY KEY (`id`)
)